environment: development
cloudProvider: azure
imagePullPolicy: Always
pullSecretName: acr-registry
splunkIndex: ""
resetOnConfigChange: true

authentication:
  ca:
    enabled: false
    useExternal: false
    externalSecretName: ""
  ssl:
    enabled: false
    useExternal: false
    externalSecretName: ""
  opa:
    enabled: true
    customHeaderName: ""
    domains: "3d"

route:
  enabled: true
  paths:
    pycsw: /
  tls: true

ingress:
  enabled: false
  paths:
    pycsw: /
  host: minikube.local

local:
  certs:
    ca: certs/ca.crt
    ssl: certs/openssl.cnf
    postgres:
      enabled: false
      ca: certs/postgres/rootCA.crt
      key: certs/postgres/avi.key
      cert: certs/postgres/avi.crt

postgresSecret:
  enabled: false
  useExternal: false
  externalSecretName: ""
  caFileKey: caFile
  certFileKey: certFile
  keyFileKey: keyFile
  userName: ""
  password: ""

shared:
  DB:
    Schema: public
    Host: 10.8.1.20
    Port: 6432
    Name: 3d-catalog-manager-dev
    requirePassword: true
    SSL:
      enabled: false

ports:
  pycsw:
    port: 8000
  opa:
    port: 9191
  envoy:
    port: 8111

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3
  enableLogging: false

envoy:
  image: envoyproxy/envoy
  imageTag: v1.18.3
  maxRequestBytes: 8192

pycsw:
  image: acrarolibotnonprod.azurecr.io/pycsw
  imageTag: v3.1.7
  maxrecords: null
  loglevel: WARNING
  logfile: ""
  profiles: mc3d
  env:
    logFormat: '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %({x-forwarded-for}i)s %(L)s'
    cors:
      enabled: true
      allowedOrigin: '*'
      allowedHeaders: ''
  servicePort: 8080
  internalServicePort: 80
  NODE_PORT: 30018
  replicaCount: 1
  resources:
    enabled: true
    requests:
      memory: 1Gi
      cpu: "1"
    limits:
      memory: 1Gi
      cpu: "1"