{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: 'serviceName={{ template "catalog.fullname" . }}-pycsw rewrite=/;serviceName={{ template "catalog.fullname" . }}-manager rewrite=/'
    nginx.org/location-snippets: |
      if ($request_method = OPTIONS) {
        return 204;
      }

      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Max-Age 3600;
      add_header Access-Control-Expose-Headers Content-Length;
      add_header Access-Control-Allow-Headers *;
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.paths.pycsw | default (print "/" .Release.Name "/" .Chart.Name "/pycsw") }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "catalog.fullname" . }}-pycsw
            port:
              number: {{ .Values.pycsw.ServicePort }}
      - path: {{ .Values.ingress.paths.manager | default (print "/" .Release.Name "/" .Chart.Name "/manager") }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "catalog.fullname" . }}-manager
            port:
              number: {{ .Values.manager.ServicePort }}
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host | quote }}
    {{ end }}
{{ end }}
