{{- if .Values.authentication.opa.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "catalog.fullname" . }}-opa
data:
  policy.rego: |-
{{ tpl (.Files.Get "config/policy.rego") . | b64enc | indent 4 }}
{{- end }}
