apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "catalog.fullname" . }}-shared-configmap
data:
  DB_HOST: {{ quote .Values.shared.DB.Host }}
  DB_PORT:  {{ quote .Values.shared.DB.Port }}
  DB_NAME: {{ quote .Values.shared.DB.Name }}
  DB_USE_SSL: {{ quote .Values.shared.DB.SSL.enabled }}
  DB_SCHEMA: {{ quote .Values.shared.DB.Schema }}
